ERROR:root:
Traceback (most recent call last):
  File "F:/python/venv/Include/scrap.py", line 5, in <module>
    raise Exception
Exception
